// NewsAPİAPP/src/components/news/newscard.jsx
import './news.css'
const NewsCard = () => {
  return (
    <div className="news-card-wrapper">
      <h1 className="text-center">Haberler </h1>
      <div className="container">
        <div className="card-wrapper mt-5">
          <div className="card">
            <div className="card-top">
              <img
                src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Habert%C3%BCrk_TV_logo.svg/1200px-Habert%C3%BCrk_TV_logo.svg.png"
                alt="newscard"
                className="img-fluid"
              />
            </div>

            <div className="card-content">
              <h2>Lorem, ipsum.</h2>
              <p>Lorem ipsum dolor sit.</p>
            </div>
          </div>

          <div className="card">
            <div className="card-top">
              <img
                src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Habert%C3%BCrk_TV_logo.svg/1200px-Habert%C3%BCrk_TV_logo.svg.png"
                alt="newscard"
                className="img-fluid"
              />
            </div>

            <div className="card-content">
              <h2>Lorem, ipsum.</h2>
              <p>Lorem ipsum dolor sit.</p>
            </div>
          </div>

          <div className="card">
            <div className="card-top">
              <img
                src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Habert%C3%BCrk_TV_logo.svg/1200px-Habert%C3%BCrk_TV_logo.svg.png"
                alt="newscard"
                className="img-fluid"
              />
            </div>

            <div className="card-content">
              <h2>Lorem, ipsum.</h2>
              <p>Lorem ipsum dolor sit.</p>
            </div>
          </div>

          <div className="card">
            <div className="card-top">
              <img
                src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Habert%C3%BCrk_TV_logo.svg/1200px-Habert%C3%BCrk_TV_logo.svg.png"
                alt="newscard"
                className="img-fluid"
              />
            </div>

            <div className="card-content">
              <h2>Lorem, ipsum.</h2>
              <p>Lorem ipsum dolor sit.</p>
            </div>
          </div>

          <div className="card">
            <div className="card-top">
              <img
                src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Habert%C3%BCrk_TV_logo.svg/1200px-Habert%C3%BCrk_TV_logo.svg.png"
                alt="newscard"
                className="img-fluid"
              />
            </div>

            <div className="card-content">
              <h2>Lorem, ipsum.</h2>
              <p>Lorem ipsum dolor sit.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default NewsCard

// AngularOldVersion/AngularNewsApp/src/app/components/newscard/newscard.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-newscard',
  templateUrl: './newscard.component.html',
  styleUrls: ['./newscard.component.scss']
})
export class NewscardComponent {

}

<section class="news-card">
  <div class="container">
    <h3 class="text-center fw-bold">Haberler</h3>
    <div
      class="card-wrapper d-flex justify-content-center flex-wrap gap-5 mt-5"
    >
      <div class="card">
        <div class="card-img">
          <img src="assets/lastnews.jpeg" alt="" class="img-fluid" />

          <div class="card-content text-center p-3">
            <h2 class="title">Milliyet</h2>
            <p class="desc">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit.
              Necessitatibus, eaque?
            </p>
          </div>
        </div>
      </div>

      <div class="card">
        <div class="card-img">
          <img src="assets/lastnews.jpeg" alt="" class="img-fluid" />

          <div class="card-content text-center p-3">
            <h2 class="title">Milliyet</h2>
            <p class="desc">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit.
              Necessitatibus, eaque?
            </p>
          </div>
        </div>
      </div>

      <div class="card">
        <div class="card-img">
          <img src="assets/lastnews.jpeg" alt="" class="img-fluid" />

          <div class="card-content text-center p-3">
            <h2 class="title">Milliyet</h2>
            <p class="desc">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit.
              Necessitatibus, eaque?
            </p>
          </div>
        </div>
      </div>

      <div class="card">
        <div class="card-img">
          <img src="assets/lastnews.jpeg" alt="" class="img-fluid" />

          <div class="card-content text-center p-3">
            <h2 class="title">Milliyet</h2>
            <p class="desc">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit.
              Necessitatibus, eaque?
            </p>
          </div>
        </div>
      </div>

      <div class="card">
        <div class="card-img">
          <img src="assets/lastnews.jpeg" alt="" class="img-fluid" />

          <div class="card-content text-center p-3">
            <h2 class="title">Milliyet</h2>
            <p class="desc">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit.
              Necessitatibus, eaque?
            </p>
          </div>
        </div>
      </div>
      <div class="card rounded-md">
        <div class="card-img">
          <img src="assets/lastnews.jpeg" alt="" class="img-fluid" />

          <div class="card-content text-center p-3">
            <h2 class="title">Milliyet</h2>
            <p class="desc">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit.
              Necessitatibus, eaque?
            </p>
          </div>
        </div>
      </div>

      <div class="card rounded-md">
        <div class="card-img">
          <img src="assets/lastnews.jpeg" alt="" class="img-fluid" />

          <div class="card-content text-center p-3">
            <h2 class="title">Milliyet</h2>
            <p class="desc">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit.
              Necessitatibus, eaque?
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
